### ISSUE TITLE
Not able to visualize the editor window after minimizing. [v1.3.6]

### ISSUE THREAD

**Issue by Chgv99** [pabllopf/Alis#11]
**Describe the bug**
I'm can't use the application after minimizing it when being asked for a project path. It is still shown in the taskbar though.
If I close the program by right clicking it on the taskbar and open it again I can use it normally but I can reproduce the bug again if I wanted.

**To Reproduce**
1. Open the editor
2. Once you're asked to define a path for your new project, minimize the window
3. Now you're unable to maximize it again

**Expected behavior**
The window should maximize if I clicked on it in the taskbar.

**Screenshots**
![Project path](https://user-images.githubusercontent.com/55676590/117337497-571fe400-ae95-11eb-8242-2edda4d0b4d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.3.6

**Additional context**
Downloaded *Alis_Editor_Windows.zip*

**Comment by pabllopf** [comment]
Hi Chgv99 
First of all, I would like to thank you for completing the report so completely. I have already located the problem, and it is due to a possible incompatibility of the drivers of your graphics card with the version of OpenGL that Alis uses.

I would recommend updating the drivers, and on the other hand I promise to include a new Alis Editor improvement HU to make the system more robust and avoid these incompatibilities.

Thanks
